name: stg-deploy

on:
  push:
    branches:
      - main

env:
  USERNAME: ${{secrets.BASIC_AUTH_USERNAME}}
  PASSWORD: ${{secrets.BASIC_AUTH_PASSWORD}}

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['16.4.1']

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: yarn install
        run: yarn --immutable

      - name: lint
        run: yarn lint

      - name: build
        run: yarn build

      - name: set firebase configure
        run: yarn firebase functions:config:set someservice.username=${{secrets.BASIC_AUTH_USERNAME}} someservice.password=${{secrets.BASIC_AUTH_PASSWORD}}

      - name: deploy to staging
        run: yarn deploy:staging
