name: stg-deploy

on:
  push:
    branches:
      - main

env:
  FIREBASE_TOKEN: ${{secrets.FIREBASE_TOKEN}}

jobs:
  build:
    runs-on: ubuntu-latest

   strategy:
      matrix:
        node-version: ['16.4.1']

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: yarn install
        run: yarn --immutable

      - name: lint
        run: yarn lint

      - name: build & export
        run: yarn export

      - name: deploy
        run: yarn deploy:staging --token=${{ secrets.FIREBASE_TOKEN }}
